name: CI/CD Workflow

on:
  push

jobs:
  build_develop:
    #if: startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.4

      - name: Resolve dependencies
        working-directory: ./backend
        run: npm ci

      - name: Execute unit tests
        working-directory: ./backend
        run: npm test

      - name: Tag the build
        run: |
          TAG_NAME="build-${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  build_release:
    #if: startsWith(github.ref, 'refs/tags/rc-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.4

      - name: Resolve dependencies
        working-directory: ./backend
        run: npm ci

      - name: Execute unit tests
        working-directory: ./backend
        run: npm test

      - name: Execute ESLint checks
        working-directory: ./backend
        run: npm run eslint:check
